import 'dart:async';

import 'package:cosmic_trader/data/storage/settings_storage.dart';

/// **The** clock. Nothing in the game measures game time any other way.
///
/// One tick is one pass of the 30-second loop. Every duration the player or the
/// simulation cares about is counted in ticks, never in milliseconds of wall
/// time, and the reason is not stylistic:
///
/// - **Time stops when the game is closed.** It is single-player with local
///   saves, so a month of real time between sessions is not game time and
///   nothing may accrue against it. A 24-hour interest period is 2,880 ticks of
///   *play*, which at one hour a session is two months of sessions — which is
///   exactly what the player is buying when they sit down.
/// - **Otherwise every cooldown is escapable.** A 24-hour hack ban expressed in
///   wall-clock milliseconds is a ban the player clears by quitting and
///   reopening, because the comparison is against a clock that kept running.
///   That is not a balance question, it is a missing guard.
///
/// ## Why the counter is persisted
///
/// A counter that reset to zero on launch would make every stored "expires at
/// tick N" meaningless: N would be from the previous session and `N - 0` is a
/// very large number, so nothing would ever be expired. The obvious repair —
/// clamping a negative elapsed to zero — then makes every cooldown *vacuous*
/// instead, and the ban is gone. Persisting is the only option that keeps a
/// long cooldown long.
///
/// The cost is one integer on `GameSettings`, saved on a throttle rather than
/// every tick: a crash costs at most [_saveEveryTicks] of cooldowns, which is
/// generous to the player and cannot be farmed, since restarting does not reset
/// the counter.
///
/// ## The tick↔real-time mapping
///
/// One tick is **30 seconds**, so a game hour is 120 ticks and a game day is
/// 2,880. That makes "30 minutes" 60 ticks and a 1.1% daily rate on 100,000 cr
/// an accrual of 0.38194 cr/tick — both quotable to the player without a
/// conversion table.
///
/// The Automation console can change the loop's *interval*, and that is a
/// diagnostic override only: it makes the tick fire faster for testing, and it
/// deliberately does **not** redefine how long a tick is worth. If it did, every
/// cooldown in the game would silently shorten the moment somebody opened the
/// dev console, which is the opposite of what a diagnostic tool should do.
class GameClock {
  GameClock._();

  /// Seconds one tick is worth. Const, and deliberately not derived from the
  /// tick service's (adjustable) interval — see the class doc.
  static const int secondsPerTick = 30;

  static const int ticksPerMinute = 60 ~/ secondsPerTick; // 2
  static const int ticksPerHour = ticksPerMinute * 60; // 120
  static const int ticksPerDay = ticksPerHour * 24; // 2,880
  static const int ticksPerWeek = ticksPerDay * 7;

  /// How often the counter is written to disk. See the class doc for why it is
  /// throttled and why that is not an exploit.
  static const int _saveEveryTicks = 60;

  static int _tick = 0;
  static int _sinceSave = 0;
  static bool _loaded = false;

  /// The current tick. Monotonic within a run, and across runs.
  static int get tick => _tick;

  /// Fractional ticks since the last save, for diagnostics only.
  static int get ticksSinceLastSave => _sinceSave;

  /// Loads the persisted counter. Safe to call more than once.
  ///
  /// Called from `GameShell` during startup. Everything else assumes it has run,
  /// because a cooldown read against an unloaded clock would see tick 0 and
  /// decide nothing has expired yet — which is the safe direction, and is why
  /// this is a `max` rather than an assignment below.
  static Future<void> load() async {
    if (_loaded) return;
    _loaded = true;
    try {
      // `load` returns null when the file is absent, which is also how a brand
      // new install looks. A universe with no settings file has no saved
      // cooldown to preserve, so tick 0 is the correct reading, not a fallback.
      final settings = await SettingsStorage.instance.load();
      _tick = settings?.worldTick ?? 0;
    } catch (_) {
      // A corrupt settings file is regenerated by the caller anyway.
      _tick = 0;
    }
  }

  /// Advances the clock. Called once per tick by `GameTickService`.
  ///
  /// Returns the new tick value so a caller that wants to do per-tick work does
  /// not have to read the field back.
  static Future<int> advance([int by = 1]) async {
    // Self-healing rather than trusting call order. `GameShell` starts the tick
    // in `initState` and the clock is loaded by an awaited settings read, so on
    // paper the first tick could outrun the load. In practice a file read beats
    // the 30-second interval, but "in practice" is not a guarantee, and the
    // failure would be silent: one tick counted from zero, and every cooldown
    // deadline in the save shifted by one tick forever after.
    if (!_loaded) await load();

    // A negative or zero advance is a caller bug, and honouring it would move
    // **every stored deadline backwards** \u2014 a ban, a debuff and a lottery period
    // all extending at once. Clamped rather than thrown so a bad call degrades to
    // "no time passed", which is the same direction as the tick not running.
    if (by <= 0) return _tick;

    _tick += by;
    _sinceSave += by;
    if (_sinceSave >= _saveEveryTicks) {
      await flush();
    }
    return _tick;
  }

  /// Writes the counter to disk now. Called on a throttle and at shutdown.
  static Future<void> flush() async {
    _sinceSave = 0;
    try {
      final settings = await SettingsStorage.instance.load();
      if (settings == null) return; // nothing to write into
      if (settings.worldTick == _tick) return; // already current
      await SettingsStorage.instance.save(settings.copyWith(worldTick: _tick));
    } catch (_) {
      // Losing a clock write must not break a tick or a save. The worst case is
      // a little cooldown progress, which is generous to the player and not
      // farmable.
    }
  }

  // ── Display helpers ───────────────────────────────────────────────────────
  // Ticks are the stored unit; the UI needs "2h 14m". These are the only place
  // ticks become a string, so a rate quoted to the player can never disagree
  // with the rate that was applied.

  /// `2h 14m`, `14m`, `45s` — a compact human duration for [ticks].
  static String format(int ticks) {
    if (ticks <= 0) return '0s';
    final totalSeconds = ticks * secondsPerTick;
    if (totalSeconds < 60) return '${totalSeconds}s';
    final totalMinutes = totalSeconds ~/ 60;
    if (totalMinutes < 60) return '${totalMinutes}m';
    final hours = totalMinutes ~/ 60;
    final minutes = totalMinutes % 60;
    if (hours < 24) {
      return minutes == 0 ? '${hours}h' : '${hours}h ${minutes}m';
    }
    final days = hours ~/ 24;
    final remainderHours = hours % 24;
    return remainderHours == 0 ? '${days}d' : '${days}d ${remainderHours}h';
  }

  /// Coarse play-time estimate — `~5 min`, `under a minute`, `~2 h`.
  ///
  /// Deliberately vaguer and coarser than [format], because it answers a
  /// different question. [format] is a **countdown**: the player is watching it
  /// and wants the ticks. This is a **duration**: "roughly how long will this
  /// take", shown beside a progress bar where a precise figure would imply a
  /// precision the tick cannot offer. It returns an empty string at zero so a
  /// caller can drop the parenthetical rather than print `(~0 min)`.
  ///
  /// It lived as a private `_estimateMinutes` on `PlanetScreen`, used by both the
  /// construction and transit panels — which is why it belongs here rather than
  /// beside either of them.
  static String estimate(int ticks) {
    if (ticks <= 0) return '';
    final minutes = (ticks * secondsPerTick / 60).round();
    if (minutes < 1) return 'under a minute';
    if (minutes < 60) return '~$minutes min';
    final hours = minutes / 60;
    return '~${hours.toStringAsFixed(hours < 2 ? 1 : 0)} h';
  }

  /// Ticks until [deadlineTick], floored at zero.
  static int remaining(int deadlineTick) {
    final left = deadlineTick - _tick;
    return left > 0 ? left : 0;
  }

  /// Whole [unit]-tick periods between [at] and now \u2014 i.e. "how many
  /// [unit]s ago". Negative when [at] is in the future.
  ///
  /// Exists because every "age ago" label in the UI wants the same thing in
  /// three different units (minutes, hours, days), and each one was otherwise
  /// hand-converted from a tick count at the call site \u2014 which is where the
  /// unit mistakes would live.
  static int periodsSince(int at, int unit) => (_tick - at) ~/ unit;

  /// True once [deadlineTick] has passed. A null deadline never expires, which
  /// is how an absent ban or timer reads.
  static bool hasPassed(int? deadlineTick) =>
      deadlineTick != null && _tick >= deadlineTick;

  /// True while [deadlineTick] is in the future.
  static bool isActive(int? deadlineTick) =>
      deadlineTick != null && _tick < deadlineTick;

  /// Test seam. Resets the counter so one test's ticks cannot vouch for
  /// another's assertions — the same shared-singleton trap as the action log.
  static void resetForTest([int to = 0]) {
    _tick = to;
    _sinceSave = 0;
    _loaded = true;
  }
}
