import 'dart:math' as math;

class NpcNameGenerator {
  static const List<String> factionFirstNames = [
    "Korgath",
    "T'Pral",
    "Quarkis",
    "Garoth",
    "Lwaxana",
    "Zevok",
    "Wicketta",
    "Vornak",
    "Salat",
    "Tuvix",
    "Brakiss",
    "J'onnar",
    "Qweev",
    "Lirath",
    "M'pok",
    "Sybok",
    "Dukat",
    "N'vek",
    "Romara",
    "Chirpa",
    "T'Lara",
    "Vorin",
    "Grelok",
    "Feris",
    "Betara",
    "Kweej",
    "Torg",
    "Vulan",
    "Zorin",
    "Yaddlek",
    "Grilka",
    "S'var",
    "Porgo",
    "Nelix",
    "Tarkon",
    "Worfek",
    "L'Rell",
    "Vexis",
    "Q'Tar",
    "Logray",
    "Sarek",
    "Damara",
    "Krillix",
    "T'Vok",
    "Gornath",
    "Zekara",
    "B'Elan",
    "Vorok",
    "Tweeka",
    "Jarak",
    "Jaxon",
    "Kai",
    "Leo",
    "Zane",
    "Axel",
    "Ronan",
    "Nico",
    "Orion",
    "Cyrus",
    "Kian",
    "Elara",
    "Lyra",
    "Nova",
    "Aria",
    "Seraphina",
    "Astrid",
    "Thalia",
    "Zara",
    "Iris",
    "Juniper",
    "Ghorak",
    "Vrakul",
    "Thokarr",
    "Drazan",
    "Krogan",
    "Vraxos",
    "Karthak",
    "Durgath",
    "Sylae",
    "Aelara",
    "Thalindra",
    "Vaelis",
    "Ilyara",
    "Sylvara",
    "Aethel",
    "Liora",
  ];

  static const List<String> factionLastNames = [
    "K'tar",
    "V'lar",
    "Zolak",
    "Duras",
    "Troi'el",
    "Yubnub",
    "Skrain",
    "T'Pol",
    "Quarkon",
    "Moghra",
    "V'tek",
    "Wompat",
    "Garakith",
    "T'varis",
    "Bruntok",
    "Korgon",
    "L'Raan",
    "Zev'rok",
    "Tarkis",
    "S'vok",
    "Deanna'ra",
    "Wicketar",
    "Vorath",
    "Gul'ek",
    "T'Lani",
    "Romulak",
    "B'Tor",
    "Zibber",
    "Kweevok",
    "Martok",
    "Vulanis",
    "Porgath",
    "S'laris",
    "Chirpok",
    "T'Rell",
    "Gornok",
    "Ferengi'ok",
    "Yaddlek",
    "Krillara",
    "V'Kor",
    "Lograth",
    "Betazoidis",
    "Q'Tal",
    "Worfak",
    "Tuvokis",
    "Zek'ra",
    "Damarok",
    "Sybokar",
    "J'onnok",
    "Brakith",
    "Volkov",
    "Orlov",
    "Stark",
    "Vance",
    "Cross",
    "Valerius",
    "Blackwood",
    "Dresden",
    "Kincaid",
    "Thorne",
    "Vega",
    "Ryder",
    "Corbin",
    "Silas",
    "Drake",
    "Sterling",
    "Lander",
    "Creed",
    "Joric",
    "Griffin",
  ];

  static const List<String> pirateFirstNames = [
    "Bloodfang",
    "Voidreaver",
    "Skullbreaker",
    "Razorjaw",
    "Ironhide",
    "Grimfang",
    "Stormrider",
    "Shadowclaw",
    "Darkbane",
    "Runebreaker",
    "Nightmare",
    "Deathcoil",
    "Ironfist",
    "Skullsplitter",
    "Bonecrusher",
    "Gorehowl",
    "Ravager",
    "Doomhammer",
    "Deathwing",
    "Blackscourge",
    "Voidwalker",
    "Nightreaper",
    "Stormfang",
    "Shadowbane",
    "Darkclaw",
  ];

  static const List<String> pirateLastNames = [
    "the Cruel",
    "the Vile",
    "the Ruthless",
    "the Merciless",
    "the Dread",
    "of the Void",
    "of the Abyss",
    "of the Dark",
    "of the Storm",
    "of the Night",
    "Bloodbane",
    "Skullmaw",
    "Deathbringer",
    "Goretooth",
    "Ironjaw",
    "Stormfang",
    "Shadowbane",
    "Darkclaw",
    "Voidwalker",
    "Nightreaper",
  ];

  static const List<String> shipNames = [
    "Starhawk",
    "Voidrunner",
    "Iron Maw",
    "Stormbreaker",
    "Dark Phoenix",
    "Nebula Drifter",
    "Solar Wind",
    "Cosmic Ray",
    "Plasma Edge",
    "Quantum Leap",
    "Void Serpent",
    "Starfire",
    "Shadow Wing",
    "Thunderbolt",
    "Frostbite",
    "Nova Strike",
    "Celestial Blade",
    "Astral Wind",
    "Dark Pulse",
    "Starfall",
    "Void Hunter",
    "Storm's Edge",
    "Iron Claw",
    "Shadow Dancer",
    "Thunder's Call",
    "Frost Guardian",
    "Nova's Wrath",
    "Celestial Fury",
    "Astral Storm",
    "Dark Torrent",
    "Void's Bane",
    "Star's Edge",
    "Storm's Wrath",
    "Iron's Will",
    "Shadow's End",
  ];

  static String generatePilotName({bool isPirate = false, int? seed}) {
    final rng = seed != null ? math.Random(seed) : math.Random();
    if (isPirate) {
      return '${pirateFirstNames[rng.nextInt(pirateFirstNames.length)]} '
          '${pirateLastNames[rng.nextInt(pirateLastNames.length)]}';
    }
    return '${factionFirstNames[rng.nextInt(factionFirstNames.length)]} '
        '${factionLastNames[rng.nextInt(factionLastNames.length)]}';
  }

  static String generateShipName({int? seed}) {
    final rng = seed != null ? math.Random(seed) : math.Random();
    return shipNames[rng.nextInt(shipNames.length)];
  }
}
